### ISSUE TITLE
0.6.0 release TODO

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#136]
Looks like the 0.6.0 release of ROM will be even bigger than 0.5.0. This, just like previously, also includes updates to all adapters and rom-rails. There's a lot of stuff to do "around" the release so I'm listing them here for a reference and in case somebody would like to help:

- [x] finish #122
- [x] finish #155 
- [x] finish rom-rb/rom-rails#25
- [x] add missing yard docs for new and changed interfaces in rom core
- [x] add yard docs to rom-sql
- [x] add yard docs to rom-rails
- [x] update rom-rb.org's introductory articles to reflect changes in APIs
- [x] update rom-rb.org's Rails tutorial to work with 0.6.0
- [x] update README's and make sure examples are up-to-date
- [x] update ALL THE CHANGELOGS
- [x] prepare rom-rails, rom-sql and rom-mongo for a new release (check gemspecs wrt dependencies, version numbers etc.)
- [x] prepare csv and yaml adapters for a release (update READMEs, gemspecs, version numbers etc.)
- [x] put together release blog post with upgrade notes (might be better to describe upgrade process in a separate article or maybe start using wiki on github for that, thoughts?)
- [x] *I definitely forgot about something* so lemme know if you think something is missing

/cc @elskwid @splattael @aflatter

**Comment by aflatter** [comment]
(Changelogs need to be updated too)

**Comment by solnic** [comment]
@aflatter ugh of course :) thanks for the reminder, I updated todos

**Comment by solnic** [comment]
OK it feels like releasing beta versions of rom, rom-sql and rom-rails will be a good start. Beta or a RC (I consider APIs as frozen, the only thing I'd like to add is #155).

During beta/rc phase people could try it out and some potential silly issues that we might've missed could be fixed. Then final version could be released.

With so many changes I think it's a good way to go. We could just tweet about beta/rc releases and ask people in the chat to try it out. Blog ann posts would be published for the final releases.

**Comment by cored** [comment]
@solnic isn't better for tracking to have the items as separate issues?

**Comment by solnic** [comment]
@cored this issue is just a todo list to prep the release. Any problems discovered should be reported as separate issues

**Comment by solnic** [comment]
Just a quick update: rom 0.6.0.beta2, rom-sql 0.4.0.beta1 and rom-rails 0.3.0.beta1 are released now. I haven't had the time to release other adapters though but *they will be released* along with final version of rom 0.6.0 so don't worry.
