### ISSUE TITLE
0.8.0 release plan

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#253]
This release is going to be massive wrt number of gems that are going to be pushed and additional work related to the guides on the website. Most of the heavy work is done already so I'm targeting next Wednesday - June 3, as a super optimistic release date ;). More realistic vision is to wrap it up over the weekend and push on Tuesday June 9th (I'm traveling on the 8th).

### TODO

- [x] wrap up `Command::Graph` work in rom (this is almost ready, just needs polishing)
- [x] wrap up mapper improvements in rom (nepalez is doing fantastic stuff with new transformations like fold, unfold, ungroup etc.)
- [x] fix warning about circular deps in *transproc* and release transproc 0.2.3 and make rom 0.8.0 depend on it
- [x] fix rom-rails so that it still supports `repositories` with deprecation warnings (I just renamed everything to `gateways` which breaks things w/o warning :()
- [x] quick wins in rom #242 #251
- [x] prepare *all adapters* for new releases (everything was updated to work with `Gateway` already, so it's a matter of bumping versions, updating changelogs, making sure gemspecs are correct etc.)
- [x] make sure that all gemspecs point to correct versions of rom in adapters and integration gems (rails, lotus, roda)
- [x] finish rom-roda updating it to use gateway rom-rb/rom-roda#1
- [x] prepare CHANGELOGs /o\
- [x] push gems, make sure all installs w/o issues
- [x] prepare a release blog post
- [x] finish guides and updates of the website so that we can publish it along with the gem release rom-rb/rom-rb.org#71
- [x] publish
