### ISSUE TITLE
Deprecate & remove ad-hoc compositions

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom#415]
Since early version of rom-repository we supported so called ad-hoc composition of relations, which means in practice that you can compose aggregates without defining associations. This involves inferring FKs and attribute names using naming conventions. This was useful when we didn't have associations, but now it's completely unnecessary. Furthermore this costs us A LOT of additional complexity throughout the code. Now that we have associations, and they are about to be available to all adapters, we can remove ad-hoc composition support and simplify a lot of code.

### TODO

- [x] deprecate ad-hoc composition in rom-repository in `Combine` and `Wrap` relation proxy extensions (rom-repository 1.0)
- [x] remove all code that is responsible for handling combine and wrap without associations
- [x] make sure we use schemas to retrieve PKs/FKs and attribute names consistently across the whole code base

**Comment by solnic** [comment]
k this is done in master, I added deprecation warnings to rom-3 and rom-repository-1.3 so I'll push new releases soon.
